"""System B SQLAlchemy model registry."""

from src.modules.persistence.models.base import (
    AdminAction,
    AttemptRecord,
    AuthorizationTrace,
    Consent,
    Declaration,
    DocumentBundle,
    EventStore,
    IntegrationCorrelation,
    JourneyInstance,
    Membership,
    Notification,
    ProcessingConfigurationLineage,
    ReportingSnapshot,
    Request,
    RequestDocument,
    RequestParty,
    RequestSnapshot,
    RequestedServiceItem,
    ResultPackage,
    ResumeRestartDecision,
    RetryEscalationRecord,
    RuleVersion,
    ServiceConfigurationVersion,
    ServiceDefinition,
    SupportCase,
    Tenant,
    User,
)
from src.modules.persistence.db import Base

__all__ = [
    "AdminAction",
    "AttemptRecord",
    "AuthorizationTrace",
    "Base",
    "Consent",
    "Declaration",
    "DocumentBundle",
    "EventStore",
    "IntegrationCorrelation",
    "JourneyInstance",
    "Membership",
    "Notification",
    "ProcessingConfigurationLineage",
    "ReportingSnapshot",
    "Request",
    "RequestDocument",
    "RequestParty",
    "RequestSnapshot",
    "RequestedServiceItem",
    "ResultPackage",
    "ResumeRestartDecision",
    "RetryEscalationRecord",
    "RuleVersion",
    "ServiceConfigurationVersion",
    "ServiceDefinition",
    "SupportCase",
    "Tenant",
    "User",
]
